# Generated by Django 4.2 on 2023-04-14 12:27

from django.db import migrations, models
import django.db.models.deletion
import trackermanage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('assetid', models.AutoField(primary_key=True, serialize=False)),
                ('assettype', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetname', models.CharField(max_length=50)),
                ('assetcode', models.CharField(default=trackermanage.models.get_asset_code, editable=False, max_length=20)),
                ('assetimage', models.ImageField(default=None, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assettype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackermanage.assettype')),
            ],
        ),
    ]
